#!/usr/bin/env bash
set -e -o pipefail
trap 'x=$?; echo 1>&2 "FAILED ($x)."; exit $x' 0

relbranch=gh-pages

die() { local exitcode="$1"; shift; echo 1>&2 "$@"; trap '' 0; exit $exitcode; }

#   Install Haskell Stack if necessary and ensure it's in $PATH.
install_stack() {
    stackbin=~/.local/bin
    mkdir -p "$stackbin"
    export PATH=~/.local/bin:$PATH
    stack --version 2>/dev/null || {
        echo "Installing stack to $stackbin/"
        echo "This may need to sudo to install additional OS packages."
        curl -sSL https://get.haskellstack.org/ | sh -s - -d "$stackbin"
    }
}

commit_release_branch=false
while true; do case "$1" in
    -C)                 shift; git clean -fdx;;
    --branch-release)   shift; commit_release_branch=true;;
    -*)                 die 2 "Error: unknown option: '$1'";;
    *)                  break;;
esac; done
[[ ${#@} -eq 0 ]] || die 2 "Error: extra arguments:" "$@"

basedir=$(cd "$(dirname "$0")" && pwd -P)
cd "$basedir"

install_stack
stack upgrade
stack build
#   `site build` does an incremental build that assumes that the site
#   compiler hasn't changed. We need `rebuild` in case it has. (An
#   optimization would be to detect whether the site compiler has
#   changed or not.)
stack exec site rebuild

$commit_release_branch && {
    echo "Committing built site in _site/ to $relbranch"
    bin/git-commit-filetree "$relbranch" _site/
}

trap '' 0
