#!/usr/bin/env bash
set -e -o pipefail
trap 'x=$?; echo 1>&2 "FAILED ($x)."; exit $x' 0

relbranch=gh-pages

die() { local exitcode="$1"; shift; echo 1>&2 "$@"; trap '' 0; exit $exitcode; }

#   Install Haskell Stack if necessary and ensure it's in $PATH.
install_stack() {
    stackbin=~/.local/bin
    mkdir -p "$stackbin"
    export PATH=~/.local/bin:$PATH
    stack --version 2>/dev/null || {
        echo "Installing stack to $stackbin/"
        echo "This may need to sudo to install additional OS packages."
        curl -sSL https://get.haskellstack.org/ | sh -s - -d "$stackbin"
    }
}

commit_release_branch=false
while true; do case "$1" in
    --branch-release)   shift; commit_release_branch=true;;
    -*)                 die 2 "Error: unknown option: '$1'";;
    *)                  break;;
esac; done
[[ ${#@} -eq 0 ]] || die 2 "Error: extra arguments:" "$@"

basedir=$(cd "$(dirname "$0")" && pwd -P)
cd "$basedir"

install_stack
stack upgrade
stack build
#   A rebuilt site compiler doesn't know how it's been changed, and so
#   doesn't know what parts of the site need to be rebuilt. So just
#   rebuild everything; most of the time is site compiler startup
#   anyway. If you're only changing site content, you probably want to
#   be using `stack exec site watch`.
rm -rf _cache _site
stack exec site build

$commit_release_branch && {
    echo "Committing built site in _site/ to $relbranch"
    bin/git-commit-filetree "$relbranch" _site/
}

trap '' 0
