#!/usr/bin/env bash
set -e -o pipefail

basedir=$(cd "$(dirname "$0")" && pwd -P)
cd "$basedir"

trap 'echo 1>&2 FAILED.; exit 1;' 0

stackbin=~/.local/bin
mkdir -p "$stackbin"
export PATH=~/.local/bin:$PATH
stack --version 2>/dev/null || {
    echo "Installing stack to $stackbin/"
    echo "This may need to sudo to install additional OS packages."
    curl -sSL https://get.haskellstack.org/ | sh -s - -d "$stackbin"
}

stack upgrade
stack build
stack exec site build 

trap '' 0
